services:
  ai-site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV_FILE: .env.jp
    container_name: ai-site-jp
    restart: unless-stopped
    ports:
      - "4001:3000"
    env_file:
      - .env.jp
